### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dongyuanlongwang** [dongyuanlongwang/coder#207]
# TODO
## java 8 新特性

- [ ]  [Java 8 集合的 Streams 使用示例](http://www.oschina.net/code/snippet_12_34780) 
- [ ] [Java 8 日期/时间（Date Time）API指南](http://www.codeceo.com/article/java-8-date-time-api.html)

- [ ] Optional

## Nio
- [ ] [Java BIO、NIO、AIO 学习](http://stevex.blog.51cto.com/4300375/1284437)

## spring
- [ ] spring boot 的war包方式，和servlet3.0规范
- [ ] Lookup

## java 基础

3.  [过Jvm获得端口号] (http://note.youdao.com/noteshare?id=9ed5f54d10b1a1c7c9d7f529beb06c5f&sub=6EEC94FAC1764BF382A6DC5C16CFA89B
)

### 锁
lockable

### guava
CacheBuilder http://note.youdao.com/noteshare?id=fc46ae13624dc2b78462f65b9ac2d5fb&sub=43B39860FA5743429337937BBDCF08C8

### druid 源码查阅
