### ISSUE TITLE
阿里巴巴面试2018-11-08

### ISSUE THREAD

**Issue by dongyuanlongwang** [dongyuanlongwang/coder#444]
## 项目经验
- [x]  介绍一下做过的 高并发和分布式的系统。
- [ ] zk原理 #57 
- [ ] redis 集群如何保证操作的原子性 #443
## 数据结构和算法
- [x]  ConcurrentHashMap #368 
- [x] HashMap #61
- [ ] HashMap中为2的幂数的原因 #442
- [x]  一致性hash #108 
 
## jvm
- [x]  java 内存结构 #419 
- [ ] String x=new String("xxxx"); 和java内存结构的关系 #439
- [ ] 出现了oom的分析方式 #441
- [ ] jvm fullGC 频繁如何定位   #440

## concurrent
- [x] 线程池参数配比 #412 
- [ ] ReentrantLock vs synchronized #438
- [ ] ThreadLocal #25 
## nio
- [ ] BIO NIO AIO 等 #128
